version: '3.4'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../data:/var/lib/postgresql/data

  payment:
    container_name: paymentAPI
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
